
// Auto-generated by gen-rollup-cards.js
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import postcss from 'rollup-plugin-postcss';
import terser from '@rollup/plugin-terser';
import path from 'path';

export default [
  {
    input: "apps/based/card/cards/app/app-card.js",
    output: {
      file: "dist/apps/based/card/cards/app/app-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/apps/apps-card.js",
    output: {
      file: "dist/apps/based/card/cards/apps/apps-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/audio/audio-card.js",
    output: {
      file: "dist/apps/based/card/cards/audio/audio-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/bs/bs-card.js",
    output: {
      file: "dist/apps/based/card/cards/bs/bs-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/bs-commands/bs-commands-card.js",
    output: {
      file: "dist/apps/based/card/cards/bs-commands/bs-commands-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/error/error-card.js",
    output: {
      file: "dist/apps/based/card/cards/error/error-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/file/file-card.js",
    output: {
      file: "dist/apps/based/card/cards/file/file-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/github/github-card.js",
    output: {
      file: "dist/apps/based/card/cards/github/github-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/gpt/gpt-card.js",
    output: {
      file: "dist/apps/based/card/cards/gpt/gpt-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/help/help-card.js",
    output: {
      file: "dist/apps/based/card/cards/help/help-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/image/image-card.js",
    output: {
      file: "dist/apps/based/card/cards/image/image-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/markdown/markdown-card.js",
    output: {
      file: "dist/apps/based/card/cards/markdown/markdown-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/meme/meme-card.js",
    output: {
      file: "dist/apps/based/card/cards/meme/meme-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/points/points-card.js",
    output: {
      file: "dist/apps/based/card/cards/points/points-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/pond/pond-card.js",
    output: {
      file: "dist/apps/based/card/cards/pond/pond-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/roll/roll-card.js",
    output: {
      file: "dist/apps/based/card/cards/roll/roll-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/snaps/snaps-card.js",
    output: {
      file: "dist/apps/based/card/cards/snaps/snaps-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/spell/spell-card.js",
    output: {
      file: "dist/apps/based/card/cards/spell/spell-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/transfer/transfer-card.js",
    output: {
      file: "dist/apps/based/card/cards/transfer/transfer-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/url/url-card.js",
    output: {
      file: "dist/apps/based/card/cards/url/url-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/video/video-card.js",
    output: {
      file: "dist/apps/based/card/cards/video/video-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/videochat/videochat-card.js",
    output: {
      file: "dist/apps/based/card/cards/videochat/videochat-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/website/website-card.js",
    output: {
      file: "dist/apps/based/card/cards/website/website-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/youtube/youtube-card.js",
    output: {
      file: "dist/apps/based/card/cards/youtube/youtube-card.js",
      format: "es",
      sourcemap: true
    },
    plugins: [
      resolve(),
      commonjs(),
      terser()
    ]
  },

  {
    input: "apps/based/card/cards/app/app-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/app/app-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/apps/apps-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/apps/apps-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/audio/audio-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/audio/audio-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/bs/bs-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/bs/bs-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/bs-commands/bs-commands-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/bs-commands/bs-commands-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/error/error-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/error/error-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/file/file-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/file/file-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/github/github-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/github/github-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/gpt/gpt-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/gpt/gpt-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/help/help-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/help/help-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/image/image-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/image/image-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/markdown/markdown-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/markdown/markdown-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/meme/meme-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/meme/meme-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/points/points-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/points/points-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/pond/pond-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/pond/pond-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/roll/roll-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/roll/roll-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/snaps/snaps-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/snaps/snaps-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/spell/spell-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/spell/spell-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/transfer/transfer-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/transfer/transfer-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/url/url-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/url/url-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/video/video-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/video/video-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/videochat/videochat-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/videochat/videochat-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/website/website-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/website/website-card.css"), minimize: true, sourceMap: true })
    ]
  },

  {
    input: "apps/based/card/cards/youtube/youtube-card-style.js",
    output: {
      file: "dist/dummy-card-css.js",
      format: "es",
      sourcemap: false
    },
    plugins: [
      postcss({ extract: path.resolve("dist/apps/based/card/cards/youtube/youtube-card.css"), minimize: true, sourceMap: true })
    ]
  }
];
