export default {
  spells: [
    {
      name: 'zalgo',
      label: 'Zalgo',
      icon: '👹',
      description: 'Corrupts text with chaotic glyphs.',
      cost: 10,
      costText: '🪙3',
      costSymbol: 'B.webp,B.webp',
      config: {
        targets: ['self', 'buddy'],
        intensity: { type: 'number', label: 'Intensity', value: 10, min: 1, max: 50 },
      },
    },
    /*
    {
      name: 'ebublio',
      description: 'Traps target in a bubble.',
      cost: 60,
      costText: '🪙2',
      config: { duration: { type: 'number', label: 'Duration (seconds)', value: 30, min: 10, max: 300 } },
    },
    */
    {
      name: 'cure',
      label: 'Cure',
      icon: '💊',
      description: 'Removes a curse from the target.',
      cost: 20,
      costText: '🪙4',
      costSymbol: 'W.webp',
      config: { targets: ['self'] },
    },
    {
      name: 'rickroll',
      label: 'Rickroll',
      icon: '🎵',
      description: 'Plays a classic prank video.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'U.webp',
      config: {
        targets: ['self'],
        url: { type: 'text', label: 'Video URL', value: 'https://youtu.be/dQw4w9WgXcQ' },
      },
    },
    {
      name: 'forbiddenRickRoll',
      label: 'Forbidden Rickroll',
      icon: '🔒',
      description: 'An inescapable prank video.',
      cost: 30,
      costText: '🪙2',
      costSymbol: 'B.webp,U.webp,G.webp',
      config: { targets: ['self'] },
    },
    {
      name: 'lightning',
      label: 'Lightning',
      icon: '⚡️',
      description: 'Strikes with a dazzling bolt.',
      cost: 80,
      costText: '🪙3',
      costSymbol: 'R.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        intensity: { type: 'number', label: 'Intensity', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'fireball',
      label: 'Fireball',
      icon: '🔥',
      description: 'Hurls a fiery projectile.',
      cost: 80,
      costText: '🪙3',
      costSymbol: 'R.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        power: { type: 'number', label: 'Power', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'earthquake',
      label: 'Earthquake',
      icon: '🌍',
      description: 'Shakes the ground beneath.',
      cost: 80,
      costText: '🪙3',
      costSymbol: 'R.webp,G.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        magnitude: { type: 'number', label: 'Magnitude', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'flood',
      label: 'Flood',
      icon: '🌊',
      description: 'Covers the area in water.',
      cost: 80,
      costText: '🪙3',
      costSymbol: 'U.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        depth: { type: 'number', label: 'Depth', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'vortex',
      label: 'Vortex',
      icon: '🌪️',
      description: 'Creates a swirling wind.',
      cost: 80,
      costText: '🪙3',
      costSymbol: 'U.webp,R.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        strength: { type: 'number', label: 'Strength', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'barrelRoll',
      label: 'Barrel Roll',
      icon: '🎢',
      description: 'Performs a barrel roll.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'U.webp, R.webp',
      config: { targets: ['self', 'buddy', 'pond'] },
    },
    {
      name: 'alert',
      label: 'Alert',
      icon: '📢',
      description: 'Displays a custom message.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'W.webp',
      config: {
        targets: ['self', 'buddy'],
        text: { type: 'text', label: 'Message', value: 'You have been cursed!' },
      },
    },
    {
      name: 'logout',
      label: 'Logout',
      icon: '🚪',
      description: 'Forces the target to log out.',
      cost: 250,
      costText: '🪙5',
      costSymbol: 'B.webp',
      config: { },
    },
  ],

  curses: [
    {
      name: 'babel',
      label: 'Babel.js',
      icon: '🗣️',
      description: 'Scrambles communication.',
      cost: 120,
      costText: '🪙3',
      costSymbol: 'U.webp, B.webp',
      config: {
        targets: ['self'],
        duration: { type: 'number', label: 'Curse Duration', value: 1, min: 1, max: 5 },
      },
    },
    {
      name: 'riddikulus',
      label: 'Riddikulus',
      icon: '😂',
      description: 'Turns fears into something funny.',
      cost: 60,
      costText: '🪙2',
      costSymbol: 'U.webp, B.webp',
      config: {
        targets: ['self'],
        duration: { type: 'number', label: 'Duration (seconds)', value: 1, min: 1, max: 5 },
      },
    },
    {
      name: 'no-uploads',
      label: 'No Uploads',
      icon: '🚫',
      description: 'Prevents uploads for a duration.',
      cost: 150,
      costText: '🪙5',
      costSymbol: 'B.webp, W.webp',
      config: {
        duration: { type: 'number', label: 'Curse Duration', value: 1, min: 1, max: 5 },
      },
    },
    {
      name: 'banhammer',
      label: 'Banhammer',
      icon: '🔨',
      description: 'Temporarily bans the target.',
      cost: 1000,
      costText: '🪙10',
      costSymbol: 'W.webp,B.webp',
      config: {
        duration: { type: 'number', label: 'Ban Duration (seconds)', value: 600, min: 300, max: 86400 },
      },
    },
  ],

  memes: [
    {
      name: 'chicken-jockey',
      label: 'Chicken Jockey',
      icon: '🐔',
      description: 'Summons a chicken jockey.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'G.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        duration: { type: 'number', label: 'Duration (seconds)', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'hamster-dance',
      label: 'Hamster Dance',
      icon: '🐹',
      description: 'Plays a funny hamster dance sound.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'G.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        volume: { type: 'number', label: 'Volume', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'cappuccino-assassino',
      label: 'Cappuccino Assassino',
      icon: '☕',
      description: 'Summons a cappuccino assassin.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'B.webp, R.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        duration: { type: 'number', label: 'Duration (seconds)', value: 5, min: 1, max: 10 },
      },
    },
    {
      name: 'peanut-butter-jelly-time',
      label: 'Peanut Butter Jelly Time',
      icon: '🍞',
      description: 'Plays a funny peanut butter jelly time sound.',
      cost: 10,
      costText: '🪙1',
      costSymbol: 'R.webp, G.webp',
      config: {
        targets: ['self', 'buddy', 'pond'],
        volume: { type: 'number', label: 'Volume', value: 5, min: 1, max: 10 },
      },
    },
  ],
};
